@startuml smart-contract-architecture

skinparam component {
    BackgroundColor<<external>> White
    BackgroundColor<<executable>> LightGreen
}

[:core] as C

[:presentation] as P
[com.owlike:genson] as GNS <<external>>

[:chaincode] as CH
[:chaincode-org1] as CH1 <<executable>>
[:chaincode-org2] as CH2 <<executable>>
[org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim] as FABRIC <<external>>

P -up-|> C
CH -up-|> P
CH1 -up-|> CH 
CH2 -up-|> CH

GNS -|> P
FABRIC -|> CH

@enduml