@startuml system-package

skinparam component {
    BackgroundColor<<external>> White
    BackgroundColor<<test>> cyan
    BackgroundColor<<executable>> LawnGreen
}
skinparam DatabaseBackgroundColor Beige

[:core] as C0

[:chaincode] as CH
[fabric-SDK] as HF <<external>>
HF -|> CH

[:apiservice] as API
[:authmodule] as AUTH
[:chainmodule] as CHAPI
[:system-test] as SYSTEST <<test>>
[:web] as WEBAPP <<executable>>
database AuthenticationDB<<external>>

C0 <|-- CH
C0 <|-- API
API <|-- AUTH
API <|-- CHAPI 
API <|-- SYSTEST
CH <|-- SYSTEST
API <|- WEBAPP
HF <|-- CHAPI

AuthenticationDB <.right.> connection
connection <.right.> API

@enduml