services:
  # Rest api service
  api-server:
    build: ./api
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://user:pass@mongodb:27017/?authMechanism=DEFAULT
    volumes:
      - /tmp/hyperledger:/tmp/hyperledger
    networks:
      - blockchain_fabric-ca
    depends_on:
      - mongodb
      - auth-server
    links:
      - mongodb
      - auth-server

  # Authentication service
  auth-server:
    build: ./auth
    ports:
      - 8180:8180
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://user:pass@mongodb:27017/?authMechanism=DEFAULT
    networks:
      - blockchain_fabric-ca
    depends_on:
      - mongodb
    links:
      - mongodb

  # Mongodb service
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./dbdata
        target: /data/db
    networks:
      - blockchain_fabric-ca
  
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: 'verdaccio'
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    volumes:
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/plugins:/verdaccio/plugins
    networks:
      - blockchain_fabric-ca

networks:
  blockchain_fabric-ca:
    external: true
