@startuml system-package

skinparam component {
    BackgroundColor<<external>> White
    BackgroundColor<<test>> cyan
    BackgroundColor<<executable>> LawnGreen
}
skinparam DatabaseBackgroundColor Beige

[:core] as C0
[:presentation] as PS
[:chaincode-org1] as CH1
[:chaincode-org2] as CH2
[org.hyperledger.fabric-chaincode-java:\nfabric-chaincode-shim] as HFC <<external>>
[com.owlike:genson] as GS <<external>>

[:api-server] as API
[:system-test] as SYSTEST <<test>>
[:web] as WEBAPP <<executable>>
database AuthenticationDB<<external>>

C0 <|-- PS
GS -right-|> PS
PS <|-- CH1
PS <|-- CH2
HFC -right-|> CH1
HFC -right-|> CH2

C0 <|-- API
API <|-- SYSTEST
API <|-- WEBAPP
CH1 <|-- SYSTEST
CH2 <|--SYSTEST


AuthenticationDB <.up.> connection
connection <.up.> API

@enduml