name: Build And Deploy Smart Contracts

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  Build-And-Test:
    strategy:
      matrix:
        os: [ubuntu, macos]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jvm_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jvm_version }}
      - name: Build
        run: |
          cd smart-contracts
          ./gradlew classes testClasses --stacktrace
      - name: Test
        run: |
          cd smart-contracts
          ./gradlew test

  Test-Deploy:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    needs: [ Build-And-Test ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Up network and test deploy smart contracts
        run: |
          cd smart-contracts
          ./gradlew upAndDeploy --stacktrace
      - name: Shut down network
        run: |
          cd smart-contracts
          ./gradlew downNetwork --stacktrace
