name: Build And Deploy Smart Contracts

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  Build-And-Test:
    strategy:
      matrix:
        os: [ubuntu, macos]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jvm_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jvm_version }}
      - name: Build
        run: |
          cd smart-contracts
          ./gradlew classes testClasses --stacktrace
      - name: Test
        run: |
          cd smart-contracts
          ./gradlew test

  Test-Deploy:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    needs: [ Build-And-Test ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Up network and test deploy smart contracts
        run: |
          cd smart-contracts
          ./gradlew upAndDeploy --stacktrace
      - name: Shut down network
        run: |
          cd smart-contracts
          ./gradlew downNetwork --stacktrace

  Javadoc:
    if: >-
      github.event_name == 'push'
      && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release')
    runs-on: ubuntu-latest
    needs: [ Build-And-Test, Test-Deploy ]
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: api-doc
          java-version: 17
          target-folder: smart-contracts
          project: gradle
          custom-command: |
            pushd smart-contracts
            ./gradlew javadoc
            popd
            mkdir -p ./build/docs/javadoc
            cp -r ./smart-contracts/build/javadoc/ ./build/docs/javadoc
