name: Build And Deploy Smart Contracts

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd smart-contracts
          ./gradlew classes testClasses

  Javadoc:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: api-doc
          java-version: 17
          target-folder: smart-contracts
          project: gradle
          custom-command: |
            pushd smart-contracts
            ./gradlew javadoc
            popd
            mkdir -p ./build/docs/javadoc
            cp -r ./smart-contracts/build/javadoc/ ./build/docs/javadoc

  Test:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    needs: [ Build ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Test
        run: |
          cd smart-contracts
          ./gradlew test

  Test-Deploy:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    needs: [ Build ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Up network and test deploy smart contracts
        run: |
          cd smart-contracts
          ./gradlew upAndDeploy
