name: Build And Deploy Smart Contracts

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd smart-contracts
          ./gradlew classes testClasses

  Javadoc:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate javadoc
        run: |
          cd smart-contracts
          ./gradlew javadoc

  Test:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    needs: [ Build ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Test
        run: |
          cd smart-contracts
          ./gradlew test

  Test-Deploy:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    needs: [ Build ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Up network and test deploy smart contracts
        run: |
          cd smart-contracts
          sudo ./gradlew upAndDeploy
