name: Build And Deploy Smart Contracts

permissions:
  contents: write

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu]
        jvm_version: [8, 11, 17]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd smart-contracts
          ./gradlew classes testClasses
      - name: Test
        run: |
          cd smart-contracts
          ./gradlew test
#      - name: Check
#        run: |
#         cd smart-contracts
#         ./gradlew check
      - name: Up network and test deploy smart contracts
        run: |
          cd smart-contracts
          sudo ./gradlew upAndDeploy
