name: LaTeX Build and Release

on:
  push:
    branches:
      - main    
      - report
  create:
    tags:
      - "*" 

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Required LaTeX Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
      
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/
          root_file: report.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: report.pdf
  
      - name: Set Output URL
        id: release_url
        run: echo "::set-output name=url::https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ steps.create_release.outputs.id }}"