name: Compile Latex Report

on: 
  push:
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  Setup-Compile-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DanySK/compile-and-publish-all-latex@1.0.54
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

