name: compile-latex-action
run-name: Compiling github
on:
  push:
    branches:
      - main
      - report

jobs:
  compile-latex-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs/
          root_file:
            report.tex

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: docs/
          replacesArtifacts: true
          tag: ${{ steps.current-time.outputs.time }}

