Organizations:  
  - &org2
    Name: org2MSP
    ID: org2MSP
    MSPDir: $(ARTIFACTS_DIR)/org2/msp
    # Organization policies canonical path:
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
        Readers:
            Type: Signature
            Rule: "OR('org2MSP.member', 'org3MSP.member')"
        Writers:
            Type: Signature
            Rule: "OR('org2MSP.admin', 'org2MSP.client')"
        Admins:
            Type: Signature
            Rule: "OR('org2MSP.admin')"
        Endorsement:
            Type: Signature
            Rule: "OR('org2MSP.peer')"
    AnchorPeers:
        - Host: peer1-org2
          Port: 9051